-- SELECT * FROM MRL_CLIENTE WHERE SEQPESSOA = 3029 -- (Consulta o Cliente, Se Ativo, Data Cadastro, Data Ultima Compra, )
 SELECT * FROM MRL_CLIENTECARTAO WHERE  SEQPESSOATITULAR IN (3029)
-- SELECT * FROM MRL_CLIENTECREDITO  WHERE SEQPESSOA IN (3029)
-- SELECT * FROM MRL_CLIENTESEG  WHERE SEQPESSOA IN (3029)
