

SELECT * FROM MAP_MARCA M WHERE M.MARCA = 'KATIGUA'
SELECT * FROM MAP_PRODUTO P WHERE P.SEQPRODUTO = '2119897' 
SELECT * FROM MAP_FAMILIA F WHERE F.SEQFAMILIA = '189230'
-- SELECT * FROM Mbix_Tabcdistrib
