select
  u.SID,
  lower(u.OSUSER) as USER_AD,
  u.SERIAL#, 
  u.TERMINAL, 
  u.CLIENT_IDENTIFIER,
  u.PROGRAM
    from v$session u 
      where 
         u.username is not null
         and u.PROGRAM not in (
                               'AcruxMonitor.exe',
                               'AcruxMonitorService.exe',
                               'w3wp.exe',
                               'ServicoeSocialWindows.exe',
                               'CalculoFAConsole.exe',
                               'ConsincoMasterService.exe',
                               'MetaAgendadorServico.exe',
                               'NDD.Reinf.Messenger.Agent_Instance_supernorte.ex',
                               'nddConnect.Client.Connector_Conectoreventos.exe',
                               'NDDigital.eForms.B2BService.exe',
                               'NDDigital.eForms.ColdFileGenerator.Service.1.exe',
                               'NDDigital.eForms.ColdFileGenerator.Service.2.exe',
                               'NDDigital.eForms.ColdFileGenerator.Service.3.exe',
                               'NDDigital.eForms.ColdRequestDistributor.Service.',
                               'NDDigital.eForms.ColdService.exe',
                               'NDDigital.eForms.Connector.Services.exe',
                               'NDDigital.eForms.ConnectorService.exe',
                               'NDDigital.eForms.EntryDocumentsService.exe',
                               'NDDigital.eForms.ErpPrintService.exe',
                               'NDDigital.eForms.PowerBIReport.Service.exe',
                               'NDDigital.eForms.TaskRunner.Service.exe',
                               'AgenteAtualizacao.exe',
                               'ServicoImpressao.WorkerService',
                               'RHFP.exe',
                               'RHID.EXE',
                               'RHPA.exe',
                               'python3@srvora (TNS V1-V3)',
                               'oracle@srvora (J000)',
                               'oracle@srvora (J002)',
                               'oracle@srvora (J004)',
                               'plsqldev.exe',
                               'NDDigital.eTrack.Service.SearchMonitoring.exe',
                               'NDDigital.eTrack.Service.SearchProcess.exe',
                               'IonSistemas.Vendas.Integration.Service.exe',
                               'oracle@srvora (J001)',
                               'ContabilWebService.Service',
                               'Pesquisa Clientes.exe',
                               'NDDigital.eForms.DFeService.exe',
                               'ContabilWebService.Service',
                               'Conciliador.Service',
                               'AcruxDFePainel.exe')
                            order by u.OSUSER,  u.TERMINAL
           
