-- select * from tisuper_mercashop

SELECT 
ID,
GTIN,
NOME,
DEPARTAMENTO_PAI,
DEPARTAMENTO,
MARCA,
CAST(ESTOQUE AS FLOAT) AS ESTOQUE,
CAST(ESTOQUE_MINIMO AS FLOAT) AS ESTOQUE_MINIMO,
CAST(PRECO AS FLOAT) AS PRECO,
CAST(PRECO_COM_DESCONTO AS FLOAT) AS PRECO_COM_DESCONTO,
ATIVO from tisuper_mercashop where ID_LOJA = '1'
