create or replace view mflv_basenf as
select a.id_df, a.tipotabela, a.tipnotafiscal,
       a.numerodf, a.seriedf, a.nroserieecf,
       a.nroempresa, a.seqpessoa, a.dtaentrada, a.dtahoremissao,
       a.dtaemissao, a.statusdf, a.nrosegmento,
       a.modelodf, a.nrocarga, a.ufdestino,
       a.observacao, a.codgeraloper, a.nrocondicaopagto as nrocondpagto,
       a.nroformapagto, a.nrobancocobr,
       a.tipofrete, a.dtavencimento,
       a.placaveiculo, a.ufplacaveiculo, a.seqtransportador,
       a.nrocheckout, a.indemissaonf, a.nropedidovenda,
       a.dtacancelamento, a.tipdocfiscal, a.apporigem,
       a.vlrfrete_maxtransp,
       max(a.seqvendedor) as nrorepresentante,
       max(a.cfop) cfop,
       sum(nvl(a.vlrcontabil, 0)) vlrcontabil,
       sum(nvl(a.VlrContabilsemfunrural, 0)) VlrContabilsemfunrural,
       sum(nvl(a.baseicms, 0)) baseicms,
       sum(nvl(a.vlricms, 0)) vlricms,
       sum(nvl(a.vlrisento, 0)) vlrisento,
       sum(nvl(a.vlroutras, 0)) vlroutras,
       sum(nvl(a.baseipi, 0)) baseipi,
       sum(nvl(a.vlripi, 0)) vlripi,
       sum(nvl(a.baseicmsst, 0)) baseicmsst,
       sum(nvl(a.vlricmsst, 0)) vlricmsst,
       sum(nvl(a.peraliquotaicmsst, 0)) peraliquotaicmsst,
       sum(nvl(a.vlricmsantecipado, 0)) vlricmsantecipado,
       sum(nvl(a.vlricmspresumido, 0)) vlricmspresumido,
       sum(nvl(a.vlracrfinanceiro, 0)) vlracrfinanceiro,
       sum(nvl(a.vlrisentoipi, 0)) vlrisentoipi,
       sum(nvl(a.vlroutraipi, 0)) vlroutraipi,
       sum(nvl(a.vlrfrete, 0)) vlrfrete,
       sum(nvl(a.vlrfrete, 0)) vlrfretetransp,
       sum(nvl(a.vlrseguro, 0)) vlrseguro,
       sum(nvl(a.vlrdespacessoria, 0)) vlrdespacessoria,
       sum(nvl(a.vlriss, 0)) vlriss,
       sum(nvl(a.vlrir, 0)) vlrir,
       sum(nvl(a.qtdvolume, 0)) qtdvolume,
       sum(nvl(a.pesototbruto, 0)) pesototbruto,
       sum(nvl(a.pesototliquido, 0)) pesototliquido,
       sum(nvl(a.vlrpis, 0)) vlrpis,
       sum(nvl(a.vlrcofins, 0)) vlrcofins,
       sum(nvl(a.vlrdesconto, 0)) vlrdesconto,
       sum(nvl(a.baseicms7, 0)) baseicms7,
       sum(nvl(a.baseicms12, 0)) baseicms12,
       sum(nvl(a.baseicms17, 0)) baseicms17,
       sum(nvl(a.baseicms18, 0)) baseicms18,
       sum(nvl(a.baseicms25, 0)) baseicms25,
       sum(nvl(a.vlricms7, 0)) vlricms7,
       sum(nvl(a.vlricms12, 0)) vlricms12,
       sum(nvl(a.vlricms17, 0)) vlricms17,
       sum(nvl(a.vlricms18, 0)) vlricms18,
       sum(nvl(a.vlricms25, 0)) vlricms25,
       max(a.peraliquotaicms) as peraliquotaicms,
       max(decode(a.peraliquotaicms, 7, 7, 0)) peraliquotaicms7,
       max(decode(a.peraliquotaicms, 12, 12, 0)) peraliquotaicms12,
       max(decode(a.peraliquotaicms, 17, 17, 0)) peraliquotaicms17,
       max(decode(a.peraliquotaicms, 18, 18, 0)) peraliquotaicms18,
       max(decode(a.peraliquotaicms, 25, 25, 0)) peraliquotaicms25,
       sum(nvl(a.vlracrescimo, 0)) vlracrescimo,
       sum(a.vlrfunruralitem) as vlrfunruralitem,
       max(a.peraliquotaipi) as peraliquotaipi,
       sum(a.vlrcomissao) as vlrcomissao,
       sum(a.vlritem) as vlritem,
       sum(a.vlrcsll) as vlrcsll,
       0 as vlrimpimportexport,
       a.nrointernoreceb,
       null tiprecebpedido,
       null indconcdescbaseicms,
       a.observacaolf,
       a.nfechaveacesso,
       a.seqnotafiscal,
       a.motivocancelou,
       a.statusnfe,
       a.usuemitiu,
       a.seqpessoaend seqpessoaend,
       MAX(NVL(A.VLRINDENIZACAO, 0)) AS VLRINDENIZACAO,
       SUM(NVL(A.vlritem, 0) + NVL(A.VLRACRESCIMO, 0) - NVL(A.VLRDESCONTO, 0)) AS VLRTOTITEM,
       sum(nvl(a.vlrdescicms,0)) vlrdescicms,
       sum(a.vlrvpe) vlrvpe,
       sum(a.vlricmsvpe) as vlricmsvpe,
       a.dtahorsaida as dtahorsaida,
       SUM(A.VLRDESCSF) AS VLRDESCSF,
       SUM(A.VLRDESPTRIBUTITEM) as vlrdesptributitem,
       SUM(A.VLRDESCSUFRAMA) as vlrdescsuframa,
       A.PONTOIMPRESSAOSEL AS PontoImpressaoSel,
       max(A.Pontoimpressaoautoriza) as Pontoimpressaoautoriza,
       sum(a.vlrfreteitemrateio) as vlrfreteitemrateio,
       SUM(A.VLRDESPNTRIBUTITEM) as vlrdespntributitem,
       MAX(NVL(A.VLRBASEICMSFRETETRANSP,0)) AS VLRBASEICMSFRETETRANSP,
       MAX(NVL(A.PERALIQICMSFRETETRANSP,0)) AS PERALIQICMSFRETETRANSP,
       MAX(NVL(A.VLRICMSFRETETRANSP,0)) AS VLRICMSFRETETRANSP,
       MAX(NVL(A.VLRBASEICMSFRETETERC,0)) AS VLRBASEICMSFRETETERC,
       MAX(NVL(A.PERALIQICMSFRETETERC,0)) AS PERALIQICMSFRETETERC,
       A.LINKERP,
       SUM(A.VLRDESCINCONDIC) AS VLRDESCINCONDIC,
       A.INDRETORNOCANCSEFAZ as INDRETORNOCANCSEFAZ,
       fEmbarcacaoCarga(a.seqnotafiscal, a.nroempresa) as NomeEmbarcacao,
       sum(nvl(A.vlrbaseiss, 0)) as vlrbaseiss,
       A.INDSUSPPISCOFINS AS INDSUSPPISCOFINS,
       null as seqauxnotafiscal,
       sum(nvl(a.baseicmstotnfe, 0)) baseicmstotnfe,
       sum(nvl(a.vlricmstotnfe, 0)) vlricmstotnfe,
       sum(nvl(a.baseicmssttotnfe, 0)) baseicmssttotnfe,
       sum(nvl(a.vlricmssttotnfe, 0)) vlricmssttotnfe,
       sum(a.baseicmsobssdic) as baseicmsobssdic,
       sum(a.vlricmsobssdic) as vlricmsobssdic,
       sum(nvl(a.baseipiobsadc,0)) baseipiobsadc,
       sum(nvl(a.vlripiobsadc,0)) vlripiobsadc,
       max(A.INDVLRIPIDADOADICIONAL) as INDVLRIPIDADOADICIONAL,
       null as NRODECLARAIMPORT,  null as DTAREGISTRODI, null as LOCALDESEMBARACODI,
       null as UFDESEMBARACODI,  null as DTADESEMBARACOADUANEIRODI,
       A.USUCANCELOUAUX,
       A.DTACANCELAMENTOAUX,
       A.USUCANCELOU,
       A.SEQTRANSPREDESP,
       A.SEQOPERADOR,
       A.VERSAOPESSOA,
       A.NROCARGA AS NROCARGAEXPED,
       NVL(A.NFEAMBIENTE, 'P') as NFEAMBIENTE,
       A.SEQNF,
       A.NFENROPROTENVIO,
       SUM(A.VLRSERVICO) VLRSERVICO,
       max(A.NFEDTAENV) NFEDTAENV,
       sum(nvl(A.VLRDESPESARATEIODANFE,0)) as vlrdespesarateiodanfe,
       0 as vlrimpostoimport,
       a.tipuso,
       sum(nvl(a.vlricmssttotoutrosdesp, 0)) as vlricmssttotoutrosdesp,
       sum(nvl(a.vlrfecptotoutradespnfe, 0)) as vlrfecptotoutradespnfe,
       sum(round(nvl(a.vlrpisnfe,0),2)) vlrpisnfe,
       sum(round(nvl(a.vlrcofinsnfe,0),2)) vlrcofinsnfe,
       max(a.nroregtributacao) as nroregtributacao,
       a.nfreferencianro,
       a.nfreferenciaserie,
       a.seqnfref,
       null usulancto,
       a.indfaturaicmsantec,
       max(a.indretornoevento) as indretornoevento,
       a.nfechavenova,
       a.jobnfeuser,
       a.jobnfeseg,
        max(a.dtaimpressao) dtaimpressao,
       a.jobnfeenvio,
       a.nfenroprotcancextemp,
       SUM(a.VLRDESCBONIF) AS VLRDESCBONIF,
       -- === RP 117453 ==== Inicio ====
       SUM(a.VLRTOTTRIB) AS VLRTOTTRIB,
       -- === RP 117453 ==== Fim =======
       -- === RP 118401 ==== Inicio ====
       SUM(A.VLRTOTTRIBSEMROUND) AS VLRTOTTRIBSEMROUND,
       -- === RP 118401 ==== Fim =======
       null indviatransporte,
       null vlrafrmm,
       null sepessoaadencomenda, A.INDFATCRUZADO,
       A.INDDEPOSITOFECHADO,
       a.qtddiasprazoregra,
       null indnfeajustecancel,
       a.indnfintegrafiscal,
       SUM(a.VLRPISNFESUSP) VLRPISNFESUSP,
       SUM(a.VLRCOFINSNFESUSP) VLRCOFINSNFESUSP,
       max(a.classeenquadramentoipi) classeenquadramentoipi,
       max(a.codigoenquadramentoipi) codigoenquadramentoipi,
       max(a.codigoseloipi) codigoseloipi,
       sum(a.qtdseloipi) qtdseloipi,
       SUM(A.VLRDESCSUFRAMAICMS) as VLRDESCSUFRAMAICMS,
       SUM(A.VLRDESCSUFRAMAPIS) as VLRDESCSUFRAMAPIS,
       SUM(A.VLRDESCSUFRAMACOFINS) as VLRDESCSUFRAMACOFINS,
       max(a.indcalcicmsdesonoutros) as indcalcicmsdesonoutros,
       sum(a.vlrtoticmsdesonoutros) as vlrtoticmsdesonoutros,
       sum(a.bascalcicmspartilha) as bascalcicmspartilha,
       sum(a.peraliquotafcp) peraliquotafcp,
       sum(a.peraliqintpartilhaicms) as peraliqintpartilhaicms,
       sum(a.perpartilhaicms) as perpartilhaicms,
       sum(a.vlrfcp) vlrfcp,
       sum(a.vlricmscalcdestino) vlricmscalcdestino,
       sum(a.vlricmscalcorigem) vlricmscalcorigem,
       max(a.indconsumidorfinal) indconsumidorfinal,
       0 vlrdescdespesa,
       MAX(a.observacaonfe) observacaonfe,
       '' as usulibnfdev,
       round(sum(nvl(a.vlrpiscfop,0)),2) vlrpiscfop,
       round(sum(nvl(a.vlrcofinscfop,0)),2) vlrcofinscfop,
       sum(nvl(a.vlricmssttotoutronfe, 0)) vlricmssttotoutronfe,
       sum(nvl(a.bascalcicmsstsubst, 0)) bascalcicmsstsubst,
       sum(nvl(a.vlricmsstsubst, 0)) vlricmsstsubst,
	   MAX(a.codoperador) codoperador,
       max(a.peraliqicmsdeson) as peraliqicmsdeson,
       max(a.peraliqicmsdif) as peraliqicmsdif,
       max(a.indboletonddigital) indboletonddigital,
       sum(nvl(a.BASEFCPST,0)) as basefcpst,
       max(a.PERALIQFCPST) as peraliqfcpst,
       sum(nvl(a.VLRFCPST,0)) as vlrfcpst,
       sum(nvl(a.BASEFCPICMS,0)) as basefcpicms,
       max(a.PERALIQFCPICMS) as peraliqfcpicms,
       sum(nvl(a.VLRFCPICMS,0)) as vlrfcpicms,
       sum(nvl(a.BASEFCPDISTRIB,0)) as basefcpdistrib,
       max(a.PERALIQFCPDISTRIB) as peraliqfcpdistrib,
       sum(nvl(a.VLRFCPDISTRIB,0)) as vlrfcpdistrib,
       null seqnfdevcompremessa,
       null as indsomafcpstressarc,
       max(nvl(a.vlrfcpstsubst, 0)) as vlrfcpstsubst,
       max(nvl(a.basefcpstsubst, 0)) as basefcpstsubst,
       0 as vlrfretenanf,
       a.dtahoraimp, a.dtahoraimpcanc, a.dtahoraimpdeneg,
       max(a.NumeroRECOPI) as NumeroRECOPI,
       max(a.PERDIFERIDO) as perdiferido,
       MAX(nvl(a.INDSUBTRAIICMSDESONTOTITEM, 'S')) as INDSUBTRAIICMSDESONTOTITEM,
       max(a.cnpjintermediador) as cnpjintermediador,
       max(a.nomeintermediador) as nomeintermediador,
       MAX(a.indmotivodesoicms) as indmotivodesoicms,
       sum(round(nvl(a.vlrpisissnfe,0),2)) vlrpisissnfe,
       sum(round(nvl(a.vlrcofinsissnfe,0),2)) vlrcofinsissnfe
from   mflv_dfbasefiscal a
group by  a.id_df, a.tipotabela, a.tipnotafiscal,
       a.numerodf, a.seriedf, a.nroserieecf,
       a.nroempresa, a.seqpessoa, a.dtaentrada, a.dtahoremissao,
       a.dtaemissao, a.statusdf, a.nrosegmento,
       a.modelodf, a.nrocarga, a.ufdestino,
       a.observacao, a.codgeraloper, a.nrocondicaopagto,
       a.nroformapagto, a.nrobancocobr, a.tipofrete, a.dtavencimento,
       a.placaveiculo, a.ufplacaveiculo, a.seqtransportador,
       a.nrocheckout, a.indemissaonf, a.nropedidovenda,
       a.dtacancelamento, a.tipdocfiscal, a.apporigem,
       a.vlrfrete_maxtransp,
       a.nrointernoreceb, a.observacaolf, a.nfechaveacesso,
       a.seqnotafiscal, a.motivocancelou, a.statusnfe,
       a.usuemitiu, a.seqpessoaend, a.dtahorsaida,
       A.PONTOIMPRESSAOSEL, A.LINKERP,
       A.INDRETORNOCANCSEFAZ, A.INDSUSPPISCOFINS,
       A.USUCANCELOUAUX,
       A.DTACANCELAMENTOAUX,
       A.USUCANCELOU,
       A.SEQTRANSPREDESP,
       A.SEQOPERADOR,
       A.VERSAOPESSOA,
       NVL(A.NFEAMBIENTE, 'P'),
       A.SEQNF,
       A.NFENROPROTENVIO,
       a.tipuso,
       a.nfreferencianro,
       a.nfreferenciaserie,
       a.seqnfref,
       a.indfaturaicmsantec,
       a.nfechavenova,
       a.jobnfeuser,
       a.jobnfeseg,
       a.jobnfeenvio,
       a.nfenroprotcancextemp, A.INDFATCRUZADO,
       A.INDDEPOSITOFECHADO,
       a.qtddiasprazoregra,
       a.indnfintegrafiscal,
       a.dtahoraimp, a.dtahoraimpcanc, a.dtahoraimpdeneg
Union All
select b.id_nf, b.tipotabela, b.tipnotafiscal,
       b.numeronf, b.serienf, b.nroserieecf,
       b.nroempresa, b.seqpessoa, nvl(b.dtaemissao, b.dtaentrada), nvl(b.dtahorlancto, b.dtahorentrada),
       b.dtaemissao, b.statusnf, b.nrosegmento,
       b.modelonf, null as nrocarga, null as ufdestino,
       b.observacao, b.codgeraloper, b.nrocondpagto, b.nroformapagto,
       null as nrobancocobr, b.tipfretetransp as tipofrete, b.dtavencimento,
       b.placatransp as placaveiculo, b.ufplacatransp as ufplacaveiculo, b.seqtransportador,
       null as nrocheckout, b.indemissaonf, null nropedidovenda,
       b.dtacancelamento,  b.TIPDOCFISCAL, to_number(b.apporigem),
       null vlrfrete_maxtransp,
       max(b.nrorepresentante) as nrorepresentante,
       max(b.cfop) cfop,
       sum(nvl(b.vlrcontabil, 0)) vlrcontabil,
       sum(nvl(b.VlrContabilsemfunrural, 0)) VlrContabilsemfunrural,
       sum(nvl(b.baseicms, 0)) baseicms,
       sum(nvl(b.vlricms, 0)) vlricms,
       sum(nvl(b.vlrisento, 0)) vlrisento,
       sum(nvl(b.vlroutras, 0)) vlroutras,
       sum(nvl(b.baseipi, 0)) baseipi,
       sum(nvl(b.vlripi, 0)) vlripi,
       sum(nvl(b.baseicmsst, 0)) baseicmsst,
       sum(nvl(b.vlricmsst, 0)) vlricmsst,
       sum(nvl(b.peraliquotaicmsst, 0)) peraliquotaicmsst,
       sum(nvl(b.vlricmsantecipado, 0)) vlricmsantecipado,
       sum(nvl(b.vlricmspresumido, 0)) vlricmspresumido,
       sum(nvl(b.vlracrfinanceiro, 0)) vlracrfinanceiro,
       sum(nvl(b.vlrisentoipi, 0)) vlrisentoipi,
       sum(nvl(b.vlroutraipi, 0)) vlroutraipi,
       sum(nvl(b.vlrfrete, 0)) vlrfrete,
       sum(nvl(b.vlrfrete, 0)) vlrfretetransp,
       sum(nvl(b.vlrseguro, 0)) vlrseguro,
       sum(nvl(b.vlrdespacessoria, 0)) vlrdespacessoria,
       sum(nvl(b.vlriss, 0)) vlriss,
       sum(nvl(b.vlrir, 0)) vlrir,
       sum(nvl(b.qtdvolume, 0)) qtdvolume,
       sum(nvl(b.pesototbruto, 0)) pesototbruto,
       sum(nvl(b.pesototliquido, 0)) pesototliquido,
       sum(nvl(b.vlrpis, 0)) vlrpis,
       sum(nvl(b.vlrcofins, 0)) vlrcofins,
       sum(nvl(b.vlrdesconto, 0)) vlrdesconto,
       sum(nvl(b.baseicms7, 0)) baseicms7,
       sum(nvl(b.baseicms12, 0)) baseicms12,
       sum(nvl(b.baseicms17, 0)) baseicms17,
       sum(nvl(b.baseicms18, 0)) baseicms18,
       sum(nvl(b.baseicms25, 0)) baseicms25,
       sum(nvl(b.vlricms7, 0)) vlricms7,
       sum(nvl(b.vlricms12, 0)) vlricms12,
       sum(nvl(b.vlricms17, 0)) vlricms17,
       sum(nvl(b.vlricms18, 0)) vlricms18,
       sum(nvl(b.vlricms25, 0)) vlricms25,
       max(b.peraliquotaicms) as peraliquotaicms,
       max(decode(b.peraliquotaicms, 7, 7, 0)) peraliquotaicms7,
       max(decode(b.peraliquotaicms, 12, 12, 0)) peraliquotaicms12,
       max(decode(b.peraliquotaicms, 17, 17, 0)) peraliquotaicms17,
       max(decode(b.peraliquotaicms, 18, 18, 0)) peraliquotaicms18,
       max(decode(b.peraliquotaicms, 25, 25, 0)) peraliquotaicms25,
       sum(nvl(b.vlracrescimo, 0)) vlracrescimo,
       sum(b.vlrfunruralitem) as vlrfunruralitem,
       max(b.peraliquotaipi) as peraliquotaipi,
       sum(b.vlrcomissao) as vlrcomissao,
       sum(b.vlritem) as vlritem,
       sum(b.vlrcsll) as vlrcsll,
       sum(b.vlrimpimportexport) as vlrimpimportexport,
       b.nrointernoreceb,
       b.tiprecebpedido,
       b.indconcdescbaseicms,
       b.observacaolf,
       b.nfechaveacesso,
       b.seqnotafiscal,
       b.motivocancelou,
       b.statusnfe,
       b.usuemitiu,
       nvl(b.Enderecoentrega, 0) seqpessoaend,
       MAX(NVL(B.VLRINDENIZACAO, 0)) AS VLRINDENIZACAO,
       SUM(NVL(B.VLRTOTITEM, 0)) AS VLRTOTITEM,
       sum(nvl(b.vlrdescicms,0)) + case when (b.tipnotafiscal = 'S' or B.tipuso = 'E') and nvl(b.indsubicmsdestotnf,'S') = 'S' then
                                      sum(b.vlrtoticmsdesonoutros)
                                   else
                                      0
                                   end as vlrdescicms,
       sum(b.vlrvpe) vlrvpe,
       sum(b.vlricmsvpe) as vlricmsvpe,
       B.dtasaida as dtahorsaida,
       SUM(B.VLRDESCSF) AS VLRDESCSF,
       sum(b.vlrdesptributitem) as vlrdesptributitem,
       sum(b.vlrdescsuframa) as vlrdescsuframa,
       b.PONTOIMPRESSAOSEL AS PontoImpressaoSel,
       max(b.pontoimpressaoautoriza) as Pontoimpressaoautoriza,
       sum(b.vlrfreteitemrateio) as vlrfreteitemrateio,
       sum(b.vlrdespntributitem) as vlrdespntributitem,
       0 AS VLRBASEICMSFRETETRANSP,
       0 AS PERALIQICMSFRETETRANSP,
       0 AS VLRICMSFRETETRANSP,
       0 AS VLRBASEICMSFRETETERC,
       0 AS PERALIQICMSFRETETERC,
       B.LINKERP,
       SUM(B.VLRDESCINCOND) AS VLRDESCINCONDIC,
       B.INDRETORNOCANCSEFAZ as INDRETORNOCANCSEFAZ,
       null as NomeEmbarcacao,
       sum(nvl(b.vlrbaseiss, 0)) as vlrbaseiss,
       B.INDSUSPPISCOFINS AS INDSUSPPISCOFINS,
       b.seqauxnotafiscal,
       sum(nvl(b.baseicmstotnfe, 0)) baseicmstotnfe,
       sum(nvl(b.vlricmstotnfe, 0)) vlricmstotnfe,
       sum(nvl(b.baseicmssttotnfe, 0)) baseicmssttotnfe,
       sum(nvl(b.vlricmssttotnfe, 0)) vlricmssttotnfe,
       sum(b.baseicmsobssdic) as baseicmsobssdic,
       sum(b.vlricmsobssdic) as vlricmsobssdic,
       sum(nvl(b.baseipiobsadc,0)) baseipiobsadc,
       sum(nvl(b.vlripiobsadc,0)) vlripiobsadc,
       B.INDVLRIPIDADOADICIONAL,
       B.NRODECLARAIMPORT, B.DTAREGISTRODI, B.LOCALDESEMBARACODI,
       B.UFDESEMBARACODI, B.DTADESEMBARACOADUANEIRODI,
       B.USUCANCELOUAUX,
       B.DTACANCELAMENTOAUX,
       B.USUCANCELOU,
       null as SEQTRANSPREDESP,
       NULL as SEQOPERADOR,
       B.VERSAOPESSOA,
       B.NROCARGAEXPED,
       NVL(B.NFEAMBIENTE, 'P') as NFEAMBIENTE,
       B.SEQNF,
       B.NFENROPROTENVIO,
       SUM(B.VLRSERVICO) VLRSERVICO,
       max(B.NFEDTAENV) NFEDTAENV,
       0 as vlrdespesarateiodanfe,
       sum(b.vlrimpostoimport) as vlrimpostoimport,
       b.tipuso,
       sum(nvl(b.vlricmssttotoutrosdesp, 0)) as vlricmssttotoutrosdesp,
       sum(nvl(b.vlrfecptotoutradespnfe, 0)) as vlrfecptotoutradespnfe,
       sum(round(nvl(b.vlrpisnfe,0),2)) vlrpisnfe,
       sum(round(nvl(b.vlrcofinsnfe,0),2)) vlrcofinsnfe,
       max(b.nroregtributacao) as nroregtributacao,
       b.nfreferencianro,
       b.nfreferenciaserie,
       b.seqnfref,
       b.usulancto,
       b.indfaturaicmsantec,
       null as indretornoevento,
       b.nfechavenova,
       b.jobnfeuser,
       b.jobnfeseg,
       max(b.dtaimpressao) dtaimpressao,
       b.jobnfeenvio,
       b.nfenroprotcancextemp,
       0 VLRDESCBONIF,
       -- === RP 117453 ==== Inicio ====
       SUM(B.VLRTOTTRIB) AS VLRTOTTRIB,
       -- === RP 117453 ==== Fim =======
       -- === RP 118401 ==== Inicio ====
       SUM(B.VLRTOTTRIBSEMROUND) AS VLRTOTTRIBSEMROUND,
       -- === RP 118401 ==== Fim =======
       b.indviatransporte,
       b.vlrafrmm,
       b.sepessoaadencomenda, NULL INDFATCRUZADO,
       B.INDDEPOSITOFECHADO,
       null qtddiasprazoregra,
       b.indnfeajustecancel,
       b.indnfintegrafiscal,
       SUM(b.VLRPISNFESUSP) VLRPISNFESUSP,
       SUM(b.VLRCOFINSNFESUSP) VLRCOFINSNFESUSP,
       null classeenquadramentoipi,
       null codigoenquadramentoipi,
       null codigoseloipi,
       null qtdseloipi,
       SUM(B.VLRDESCSUFRAMAICMS) as VLRDESCSUFRAMAICMS,
       SUM(B.VLRDESCSUFRAMAPIS) as VLRDESCSUFRAMAPIS,
       SUM(B.VLRDESCSUFRAMACOFINS) as VLRDESCSUFRAMACOFINS,
       max(b.indcalcicmsdesonoutros) as indcalcicmsdesonoutros,
       sum(b.vlrtoticmsdesonoutros) as vlrtoticmsdesonoutros,
       sum(b.bascalcicmspartilha) as bascalcicmspartilha,
       sum(b.peraliquotafcp) peraliquotafcp,
       sum(b.peraliqintpartilhaicms) as peraliqintpartilhaicms,
       sum(b.perpartilhaicms) as perpartilhaicms,
       sum(b.vlrfcp) vlrfcp,
       sum(b.vlricmscalcdestino) vlricmscalcdestino,
       sum(b.vlricmscalcorigem) vlricmscalcorigem,
       max(b.indconsumidorfinal) indconsumidorfinal,
       sum(b.vlrdescdespesa) vlrdescdespesa,
       MAX(b.observacaonfe) observacaonfe,
       b.usulibnfdev,
       sum(round(nvl(b.vlrpiscfop,0),2)) vlrpiscfop,
       sum(round(nvl(b.vlrcofinscfop,0),2)) vlrcofinscfop,
       sum(nvl(b.vlricmssttotoutronfe, 0)) vlricmssttotoutronfe,
       sum(nvl(b.bascalcicmsstsubst, 0)) bascalcicmsstsubst,
       sum(nvl(b.vlricmsstsubst, 0)) vlricmsstsubst,
	     MAX(b.usulancto) codoperador,
       null as peraliqicmsdeson,
       max(b.peraliqicmsdif) as peraliqicmsdif,
       max(b.indboletonddigital) indboletonddigital,
       sum(nvl(b.BASEFCPST,0)) as basefcpst,
       max(b.PERALIQFCPST) as peraliqfcpst,
       sum(nvl(b.VLRFCPST,0)) as vlrfcpst,
       sum(nvl(b.BASEFCPICMS,0)) as basefcpicms,
       max(b.PERALIQFCPICMS) as peraliqfcpicms,
       sum(nvl(b.VLRFCPICMS,0)) as vlrfcpicms,
       sum(nvl(b.BASEFCPDISTRIB,0)) as basefcpdistrib,
       max(b.PERALIQFCPDISTRIB) as peraliqfcpdistrib,
       sum(nvl(b.VLRFCPDISTRIB,0)) as vlrfcpdistrib,
       max(b.seqnfdevcompremessa) seqnfdevcompremessa,
       max(b.indsomafcpstressarc) as indsomafcpstressarc,
       max(nvl(b.vlrfcpstsubst, 0)) as vlrfcpstsubst,
       max(nvl(b.basefcpstsubst, 0)) as basefcpstsubst,
       sum(nvl(b.vlrfretenanf,0)) as vlrfretenanf,
       null dtahoraimp,null dtahoraimpcanc,null dtahoraimpdeneg,
       0 NumeroRECOPI,
       max(b.PERDIFERIDO) as PERDIFERIDO,
       MAX(nvl(b.INDSUBTRAIICMSDESONTOTITEM, 'S')) as INDSUBTRAIICMSDESONTOTITEM,
       null cnpjintermediador,
       null nomeintermediador,
       MAX(b.indmotivodesoicms) as indmotivodesoicms,
       sum(round(nvl(b.vlrpisissnfe,0),2)) vlrpisissnfe,
       sum(round(nvl(b.vlrcofinsissnfe,0),2)) vlrcofinsissnfe
from   mlfv_nfbasefiscal b
group by  b.id_nf, b.tipotabela, b.tipnotafiscal,
       b.numeronf, b.serienf, b.nroserieecf,
       b.nroempresa, b.seqpessoa, nvl(b.dtaemissao, b.dtaentrada), nvl(b.dtahorlancto, b.dtahorentrada),
       b.dtaemissao, b.statusnf, b.nrosegmento,
       b.modelonf, null, null,
       b.observacao, b.codgeraloper, b.nrocondpagto, b.nroformapagto,
       null, b.tipfretetransp, b.dtavencimento,
       b.placatransp, b.ufplacatransp, b.seqtransportador,
       null, b.indemissaonf, null,
       b.dtacancelamento, b.TIPDOCFISCAL, to_number(b.apporigem),
       b.nrointernoreceb, b.tiprecebpedido, b.indconcdescbaseicms,
       b.observacaolf,
       b.nfechaveacesso,
       b.seqnotafiscal,
       b.motivocancelou,
       b.statusnfe,
       b.usuemitiu,
       nvl(b.Enderecoentrega, 0),
       B.dtasaida,
       B.PONTOIMPRESSAOSEL, B.LINKERP,
       B.INDSUSPPISCOFINS,
       b.seqauxnotafiscal,
       B.INDVLRIPIDADOADICIONAL,
       B.NRODECLARAIMPORT, B.DTAREGISTRODI, B.LOCALDESEMBARACODI,
       B.UFDESEMBARACODI, B.DTADESEMBARACOADUANEIRODI,
       B.USUCANCELOUAUX,
       B.DTACANCELAMENTOAUX,
       B.USUCANCELOU,
       B.INDRETORNOCANCSEFAZ,
       B.VERSAOPESSOA,
       B.NROCARGAEXPED,
       NVL(B.NFEAMBIENTE, 'P'),
       B.SEQNF,
       B.NFENROPROTENVIO,
       b.tipuso,
       b.nfreferencianro,
       b.nfreferenciaserie,
       b.seqnfref,
       b.usulancto,
       b.indfaturaicmsantec,
       b.nfechavenova,
       b.jobnfeuser,
       b.jobnfeseg,
       b.jobnfeenvio,
       b.nfenroprotcancextemp,
       b.indviatransporte,
       b.vlrafrmm,
       b.sepessoaadencomenda,
       B.INDDEPOSITOFECHADO,
       b.indnfeajustecancel,
       b.indnfintegrafiscal,
       b.usulibnfdev,
       b.indsubicmsdestotnf,
       null,null,null
;
