-- SELECT * FROM TI_RFL_VW_VESTCASA;
/*
CREATE TABLE ti_rfl_tb_ticket_atendimento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero NUMBER NOT NULL,
    servico VARCHAR2(50) NOT NULL,
    empresa VARCHAR2(50) NOT NULL,
    dathoremissao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ti_rfl_tb_ticket_atendimento
MODIFY (dathoremissao DATE);
*/
insert into ti_rfl_tb_ticket_atendimento (numero,servico,empresa, dathoremissao) values (14,'Teste Glicêmico','FM01_MATRIZ',TO_DATE('2025-10-01 08:53:15', 'YYYY-MM-DD HH24:MI:SS'));





/*

select * from ti_rfl_tb_ticket_atendimento;

Select * from consinco.max_empresa e where e.nrosegmentoprinc = 6;

*/
