SELECT 
 T.CATEG_1 DEPARTAMENTO_PAI,
   sum( a.precobasenormal * (h.estqloja + h.estqdeposito)) as VLR_PRE_VENDA

FROM MRL_PRODEMPSEG     A,
     MAP_PRODUTO        D,
     MAP_FAMILIA        F,
     MAP_MARCA          G,
     MRL_PRODUTOEMPRESA H,
     TISUPER_FAMILIACATEGORIA T,
     TISUPER_PRODUTOEAN E

WHERE A.SEQPRODUTO = D.SEQPRODUTO
  AND A.SEQPRODUTO = H.SEQPRODUTO
  AND A.SEQPRODUTO = E.SEQPRODUTO
  AND A.NROEMPRESA = H.NROEMPRESA
  AND D.SEQPRODUTO = H.SEQPRODUTO
  AND D.SEQFAMILIA = F.SEQFAMILIA
  AND F.SEQFAMILIA = T.SEQFAMILIA
  AND F.SEQMARCA = G.SEQMARCA
  AND T.NRODIVISAO = 1
  AND A.NROSEGMENTO = 1
  AND A.QTDEMBALAGEM = 1
  and a.nroempresa = 1
  AND H.ESTQLOJA >= 0
  AND T.CATEG_1 NOT IN ('30 USO INTERNO','31 IMOBILIZADOS','32 RESTAURANTE','90 MATERIA PRIMA','90 SERVICOS','91 Antigo NH','92 MINI BOX','99 INATIVOS')
  group by t.CATEG_1
  order by t.CATEG_1

