-- Select nomerazao from ge_pessoa where seqpessoa = 3009
-- Select A.NROFORMAPAGTO ||  ' - ' || A.FORMAPAGTOREDUZ From MRL_FORMAPAGTO A , MRL_CLIENTECREDITO B  Where A.NROFORMAPAGTO = B.NROFORMAPAGTO And B.SEQPESSOA  = 3009 And A.STATUSFORMAPAGTO = 'A' 
-- Select FORMAPAGTO, TXAADMPERCENTUAL, SEQPESSOACONVENIO From 	MRL_FORMAPAGTO 	Where 	NROFORMAPAGTO =72	And 	ESPECIEFORMAPAGTO in  ( 'V', 'P') 
-- select MRL_CONVENIOPERIOD.NROFORMAPAGTO, MRL_CONVENIOPERIOD.SEQCONVENIOPERIOD, MRL_CONVENIOPERIOD.DTAINICIOPERIODO, MRL_CONVENIOPERIOD.DTAFIMPERIODO, MRL_CONVENIOPERIOD.DTAVENCTOPERIODO, MRL_CONVENIOPERIOD.DTAENCERRAPERIODO from MRL_CONVENIOPERIOD where NROFORMAPAGTO =72 order by DTAINICIOPERIODO Desc 
-- select * from mrl_convenioccformapagto a where a.nroformapagto=72

select * from mad_pedvenda a where a.nroempresa = 1 and a.usuinclusao like '%PEDIDO%'

