CREATE OR REPLACE VIEW TISUPER_MERCASHOP AS
SELECT DISTINCT
 A.NROEMPRESA AS ID_LOJA,
 A.SEQPRODUTO AS ID,
 E.CODACESSO AS GTIN,
 D.DESCCOMPLETA AS NOME,
 T.CATEG_1 DEPARTAMENTO_PAI,
 T.CATEG_3 DEPARTAMENTO,
 G.MARCA AS MARCA,
 REPLACE (H.ESTQLOJA - H.QTDRESERVADAVDA - H.QTDRESERVADAFIXA,',''.') AS ESTOQUE,
 REPLACE (H.ESTQMINIMOLOJA,',''.') AS ESTOQUE_MINIMO,
 REPLACE (a.precovalidnormal, ',''.') AS PRECO,
 REPLACE (NVL(A.PRECOVALIDPROMOC,0),',''.') AS PRECO_COM_DESCONTO,
 DECODE (A.STATUSVENDA,'A','S','I','N') AS ATIVO

FROM MRL_PRODEMPSEG     A,
     MAP_PRODUTO        D,
     MAP_FAMILIA        F,
     MAP_MARCA          G,
     MRL_PRODUTOEMPRESA H,
     TISUPER_FAMILIACATEGORIA T,
     TISUPER_PRODUTOEAN E

WHERE A.SEQPRODUTO = D.SEQPRODUTO
  AND A.SEQPRODUTO = H.SEQPRODUTO
  AND A.SEQPRODUTO = E.SEQPRODUTO
  AND A.NROEMPRESA = H.NROEMPRESA
  AND D.SEQPRODUTO = H.SEQPRODUTO
  AND D.SEQFAMILIA = F.SEQFAMILIA
  AND F.SEQFAMILIA = T.SEQFAMILIA
  AND F.SEQMARCA = G.SEQMARCA

  AND T.NRODIVISAO = 1
  AND A.NROSEGMENTO = 1
  AND A.QTDEMBALAGEM = 1
  and a.nroempresa = 1
  AND H.ESTQLOJA > 0
  AND T.CATEG_1 NOT IN ('14 MATERIAL CONSTRUCAO','30 USO INTERNO','31 IMOBILIZADOS','32 RESTAURANTE','90 MATERIA PRIMA','90 SERVICOS','99 INATIVOS')

  --AND A.NROEMPRESA = 1
  --AND D.INDINTEGRAECOMMERCE = 'S'  ---FILTRO PRODUTOS E-COMMERCE NA CONSINCO

ORDER BY ID
;
